In [1]:
# importing libraries to be used
import pandas as pd

In [12]:
# Create a data frame
data1={'Name': pd.Series(['Esther','Liz','John','Lin'], index=['a','b','c','d']),
       'Age': pd.Series([22,23,15,19], index=['a','b','c','d']), 'Price':pd.Series([2000,3000,4000],
      index=['a','b','d']), 'Prefered':pd.Series([True,False,True,False], index=['a','b','c','d'])}

In [68]:
data1

{'Name': a    Esther
 b       Liz
 c      John
 d       Lin
 dtype: object,
 'Age': a    22
 b    23
 c    15
 d    19
 dtype: int64,
 'Price': a    2000
 b    3000
 d    4000
 dtype: int64,
 'Prefered': a     True
 b    False
 c     True
 d    False
 dtype: bool}

Creating a dataframe

In [14]:
data2=pd.DataFrame(data1)

In [69]:
data2

     Name  Age   Price  Prefered
a  Esther   22  2000.0      True
b     Liz   23  3000.0     False
c    John   15     NaN      True
d     Lin   19  4000.0     False

Another way

In [71]:
names=['Esther','Liz','John','Lin','Ritah','Peter']
age=[22,23,15,19,23,41]
prices=[2000,3000,4000,5000,3500,6000]
preferences=[True,False,True,False,False,False]
indexes=['a','b','c','d','e','f']

In [72]:
customers_data={'Name': pd.Series(names, index=indexes), 'Age':pd.Series(age, index=indexes),
          'Price':pd.Series(prices, index=indexes),
         'Preference':pd.Series(preferences, index=indexes)}

In [73]:
customers= pd.DataFrame(customers_data)

In [74]:
customers

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False
c    John   15   4000        True
d     Lin   19   5000       False
e   Ritah   23   3500       False
f   Peter   41   6000       False

Viewing Data
Here is how to view all the data, the top and bottom rows of the frame:

In [75]:
# View All
customers

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False
c    John   15   4000        True
d     Lin   19   5000       False
e   Ritah   23   3500       False
f   Peter   41   6000       False

In [81]:
# View top
# customers.head()
customers.head(2)

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False

In [23]:
#customers.index.names=['ID']

In [82]:
# View bottom
customers.tail(2)

    Name  Age  Price  Preference
e  Ritah   23   3500       False
f  Peter   41   6000       False

Display the index, columns:

In [25]:
customers.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [83]:
customers.columns

Index(['Name', 'Age', 'Price', 'Preference'], dtype='object')

describe() shows a quick statistic summary of your data:

In [27]:
customers.describe()

             Age        Price
count   6.000000     6.000000
mean   23.833333  3916.666667
std     8.953584  1428.869017
min    15.000000  2000.000000
25%    19.750000  3125.000000
50%    22.500000  3750.000000
75%    23.000000  4750.000000
max    41.000000  6000.000000

In [84]:
customers

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False
c    John   15   4000        True
d     Lin   19   5000       False
e   Ritah   23   3500       False
f   Peter   41   6000       False

Transposing your data:

In [87]:
trasposed_data=customers.T
trasposed_data

                 a      b     c      d      e      f
Name        Esther    Liz  John    Lin  Ritah  Peter
Age             22     23    15     19     23     41
Price         2000   3000  4000   5000   3500   6000
Preference    True  False  True  False  False  False

Sorting by an axis:

In [34]:
#descending order by columns
customers.sort_index(axis=1, ascending=False)

   Price  Preference    Name  Age
a   2000        True  Esther   22
b   3000       False     Liz   23
c   4000        True    John   15
d   5000       False     Lin   19
e   3500       False   Ritah   23
f   6000       False   Peter   41

In [88]:
#Ascending order by columns
customers.sort_index(axis=1, ascending=True)

   Age    Name  Preference  Price
a   22  Esther        True   2000
b   23     Liz       False   3000
c   15    John        True   4000
d   19     Lin       False   5000
e   23   Ritah       False   3500
f   41   Peter       False   6000

In [90]:
#ascending for rows
customers.sort_index(axis=0, ascending=True)

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False
c    John   15   4000        True
d     Lin   19   5000       False
e   Ritah   23   3500       False
f   Peter   41   6000       False

In [92]:
#descednding for rows
customers.sort_index(axis=0, ascending=False)

     Name  Age  Price  Preference
f   Peter   41   6000       False
e   Ritah   23   3500       False
d     Lin   19   5000       False
c    John   15   4000        True
b     Liz   23   3000       False
a  Esther   22   2000        True

In [93]:
customers.sort_values(by='Preference')

     Name  Age  Price  Preference
b     Liz   23   3000       False
d     Lin   19   5000       False
e   Ritah   23   3500       False
f   Peter   41   6000       False
a  Esther   22   2000        True
c    John   15   4000        True

Selecting a single column, which yields a Series, equivalent to df.A:

In [95]:
customers['Name']
# customers.Name

a    Esther
b       Liz
c      John
d       Lin
e     Ritah
f     Peter
Name: Name, dtype: object

In [96]:
customers.Name

a    Esther
b       Liz
c      John
d       Lin
e     Ritah
f     Peter
Name: Name, dtype: object

In [97]:

cust_age_name=customers[['Name', 'Age']]
cust_age_name

     Name  Age
a  Esther   22
b     Liz   23
c    John   15
d     Lin   19
e   Ritah   23
f   Peter   41

In [99]:
customers

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False
c    John   15   4000        True
d     Lin   19   5000       False
e   Ritah   23   3500       False
f   Peter   41   6000       False

Selecting via [ ], which slices the rows.

In [100]:
#starting from index 0 to below index 3
customers[0:3]

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False
c    John   15   4000        True

In [39]:
customers['a':'b']

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False

Selection by Label

In [40]:
customers.loc['a']

Name          Esther
Age               22
Price           2000
Preference      True
Name: a, dtype: object

In [41]:
customers.loc[:,'Name']

a    Esther
b       Liz
c      John
d       Lin
e     Ritah
f     Peter
Name: Name, dtype: object

In [42]:
customers.loc[:,['Name','Age']]

     Name  Age
a  Esther   22
b     Liz   23
c    John   15
d     Lin   19
e   Ritah   23
f   Peter   41

In [43]:
customers.loc['b':,['Name','Age']]

    Name  Age
b    Liz   23
c   John   15
d    Lin   19
e  Ritah   23
f  Peter   41

For getting fast access to a scalar (equivalent to the prior method):

In [44]:
customers.at['b','Age']

23

In [49]:
#index loc
customers.iloc[2:4]

   Name  Age  Price  Preference
c  John   15   4000        True
d   Lin   19   5000       False

Selection by Position

Select via the position of the passed integers:

In [102]:
customers

     Name  Age  Price  Preference
a  Esther   22   2000        True
b     Liz   23   3000       False
c    John   15   4000        True
d     Lin   19   5000       False
e   Ritah   23   3500       False
f   Peter   41   6000       False

Adding two values in two columns

In [103]:
# Creating a new column called bonus which has square of the price
customers["Bonus"]=customers["Price"]*2

In [104]:
customers

     Name  Age  Price  Preference  Bonus
a  Esther   22   2000        True   4000
b     Liz   23   3000       False   6000
c    John   15   4000        True   8000
d     Lin   19   5000       False  10000
e   Ritah   23   3500       False   7000
f   Peter   41   6000       False  12000

In [105]:
customers.iloc[3]

Name            Lin
Age              19
Price          5000
Preference    False
Bonus         10000
Name: d, dtype: object

In [106]:
customers.iloc[3:5,0:2]

    Name  Age
d    Lin   19
e  Ritah   23

In [107]:
customers

     Name  Age  Price  Preference  Bonus
a  Esther   22   2000        True   4000
b     Liz   23   3000       False   6000
c    John   15   4000        True   8000
d     Lin   19   5000       False  10000
e   Ritah   23   3500       False   7000
f   Peter   41   6000       False  12000

In [ ]:
#Qn Name,Age,Price of Liz and Joh

For slicing rows explicitly:

In [108]:
customers.iloc[1:3, :]

   Name  Age  Price  Preference  Bonus
b   Liz   23   3000       False   6000
c  John   15   4000        True   8000

For slicing columns explicitly:

In [109]:
customers.iloc[:,1:3]

   Age  Price
a   22   2000
b   23   3000
c   15   4000
d   19   5000
e   23   3500
f   41   6000

Boolean Indexing

Using a single column’s values to select data.

In [110]:
cust_age_lthn20=customers[customers['Age']<20]
# customers[customers.Age<20]
cust_age_lthn20

   Name  Age  Price  Preference  Bonus
c  John   15   4000        True   8000
d   Lin   19   5000       False  10000

In [111]:
customers[(customers['Age']<20)&(customers['Price']>4000)]

  Name  Age  Price  Preference  Bonus
d  Lin   19   5000       False  10000

Using the isin() method for filtering:

In [113]:
customers[customers['Name'].isin(['Lin','Esther','Bongomin'])]

     Name  Age  Price  Preference  Bonus
a  Esther   22   2000        True   4000
d     Lin   19   5000       False  10000

In [114]:
import numpy as np

In [115]:
np.median(customers['Age'])

22.5

In [116]:
customers['Age'].apply(np.mean)

a    22.0
b    23.0
c    15.0
d    19.0
e    23.0
f    41.0
Name: Age, dtype: float64